# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokemon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpokemon.proto\x12\nou_pokemon\x1a\x1bgoogle/protobuf/empty.proto\"*\n\x0b\x42oardConfig\x12\x0b\n\x03row\x18\x01 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\x05\"\x1d\n\rMoveDirection\x12\x0c\n\x04move\x18\x01 \x01(\t\"\"\n\x0bTrainerName\x12\x13\n\x0btrainername\x18\x01 \x01(\t\"T\n\x0bTrainerInfo\x12\x13\n\x0btrainername\x18\x01 \x01(\t\x12\x13\n\x0bpokemonname\x18\x02 \x01(\t\x12\x0b\n\x03row\x18\x03 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x04 \x01(\x05\"=\n\x0bListOfMoves\x12.\n\x0bListOfMoves\x18\x01 \x03(\x0b\x32\x19.ou_pokemon.MoveDirection2\x82\x02\n\x08Pokemons\x12\x42\n\nCheckboard\x12\x17.ou_pokemon.BoardConfig\x1a\x19.ou_pokemon.MoveDirection\"\x00\x12\x38\n\x04Move\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12=\n\x07Trainer\x12\x17.ou_pokemon.TrainerName\x1a\x17.ou_pokemon.TrainerInfo\"\x00\x12\x39\n\x04Path\x12\x16.google.protobuf.Empty\x1a\x17.ou_pokemon.ListOfMoves\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pokemon_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOARDCONFIG._serialized_start=58
  _BOARDCONFIG._serialized_end=100
  _MOVEDIRECTION._serialized_start=102
  _MOVEDIRECTION._serialized_end=131
  _TRAINERNAME._serialized_start=133
  _TRAINERNAME._serialized_end=167
  _TRAINERINFO._serialized_start=169
  _TRAINERINFO._serialized_end=253
  _LISTOFMOVES._serialized_start=255
  _LISTOFMOVES._serialized_end=316
  _POKEMONS._serialized_start=319
  _POKEMONS._serialized_end=577
# @@protoc_insertion_point(module_scope)
